// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csvdaqhuoldvezqbdcnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzdmRhcWh1b2xkdmV6cWJkY251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMjAxMjQsImV4cCI6MjA2NzU5NjEyNH0.rngcvDPwZp9r0-hGpqWCu4A5lXrbwnFHa3doyfMrWvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});